version: 2

updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    groups:
      actions-deps:
        patterns:
          - "*"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
