repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-illegal-windows-names
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: destroyed-symlinks
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending

# -   repo: https://github.com/shellcheck-py/shellcheck-py
#     rev: v0.10.0.1
#     hooks:
#     -   id: shellcheck

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy

# -   repo: https://github.com/rubocop/rubocop
#     rev: v1.68.0
#     hooks:
#     -   id: rubocop

-   repo: local
    hooks:
    -   id: check-padmacros
        name: Check PADXXX macros
        entry: python3 scripts/check-pad.py
        language: python
        types_or: [c, c++]
        additional_dependencies:
        -   pcpp==1.30
        -   pycparser==2.22
