name: CI

on: [push, pull_request]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - run: autoreconf -iv
    - run: ./configure
    - run: make -j 4
    - run: make check
