name: CI

on: [push, pull_request]

jobs:
  form:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Configuration
        run: |
          autoreconf -iv
          ./configure --disable-dependency-tracking --enable-scalar --disable-threaded --disable-parform --with-gmp --with-zlib
      - name: Build
        run: make -j 4
      - name: Test
        run: ./check/check.rb ./sources/form --stat
  tform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Configuration
        run: |
          autoreconf -iv
          ./configure --disable-dependency-tracking --disable-scalar --enable-threaded --disable-parform --with-gmp --with-zlib
      - name: Build
        run: make -j 4
      - name: Test
        run: ./check/check.rb ./sources/tform --stat
  sanitize-vorm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Configuration
        run: |
          autoreconf -iv
          ./configure --disable-dependency-tracking --enable-scalar --disable-threaded --disable-parform --enable-debug --enable-sanitize --with-gmp --with-zlib
      - name: Build
        run: make -j 4 -C sources vorm
      - name: Test
        run: ./check/check.rb ./sources/vorm --stat --timeout 60
  sanitize-tvorm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Configuration
        run: |
          autoreconf -iv
          ./configure --disable-dependency-tracking --disable-scalar --enable-threaded --disable-parform --enable-debug --enable-sanitize --with-gmp --with-zlib
      - name: Build
        run: make -j 4 -C sources tvorm
      - name: Test
        run: ./check/check.rb ./sources/tvorm --stat --timeout 60
  valgrind-vorm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [examples.frm, features.frm, fixes.frm]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Prerequisite
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends valgrind
      - name: Configuration
        run: |
          autoreconf -iv
          ./configure --disable-dependency-tracking --enable-scalar --disable-threaded --disable-parform --enable-debug --with-gmp --with-zlib
      - name: Build
        run: make -j 4 -C sources vorm
      - name: Test
        run: ./check/check.rb valgrind ./sources/vorm --stat ${{ matrix.test }}
  valgrind-tvorm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: [examples.frm, features.frm, fixes.frm]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Prerequisite
        run: |
          sudo apt-get update
          sudo apt-get install -yq --no-install-recommends valgrind
      - name: Configuration
        run: |
          autoreconf -iv
          ./configure --disable-dependency-tracking --disable-scalar --enable-threaded --disable-parform --enable-debug --with-gmp --with-zlib
      - name: Build
        run: make -j 4 -C sources tvorm
      - name: Test
        run: ./check/check.rb valgrind ./sources/tvorm --stat ${{ matrix.test }}
