name: Deploy

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build-src:
    name: Build tarball distribution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensures a reachable tag

      - name: Build tarball distribution
        run: |
          distname=form-$(./scripts/git-version-gen.sh -r | sed '2q;d' | sed 's/^v//')
          autoreconf -i
          ./configure --disable-dependency-tracking --disable-scalar --disable-threaded --disable-native --without-gmp --without-zlib
          make distdir=$distname dist-gzip

      - name: Print tarball information
        run: |
          distname=form-$(./scripts/git-version-gen.sh -r | sed '2q;d' | sed 's/^v//')
          ls -l $distname.tar.gz
          file $distname.tar.gz
          tar -tf $distname.tar.gz

      - name: Upload tarball as artifact
        uses: actions/upload-artifact@v3
        with:
          name: src
          path: '*.tar.gz'
          if-no-files-found: error

  build-bin:
    name: Build ${{ matrix.bin }} on ${{ matrix.os }}
    needs: [build-src]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-18.04, macos-10.15, windows-2019]
        # bin: [form, tform]
        os: [macos-10.15,]  # for now
        bin: [form]
    steps:
      - name: Download tarball
        uses: actions/download-artifact@v3
        with:
          name: src

      - name: Configure
        run: |
          tar -xf *.tar.gz --strip-components 1
          opts='--disable-dependency-tracking --disable-scalar --disable-threaded --disable-native --enable-static-link --with-gmp --with-zlib'
          case ${{ matrix.bin }} in
            form)  opts="$opts --enable-scalar";;
            tform) opts="$opts --enable-threaded";;
          esac
          # --static fails on macOS but we want to statically link to
          # the brewed gmp. The linker supports neither -Wl,-static nor
          # -l:libgmp.a to make partial static links possible.
          # As a workaround, we make a library directory with libgmp.a
          # but without libgmp.dylib so that the linker has to link libgmp.a.
          if [ "$RUNNER_OS" == "macOS" ]; then
            mkdir static-lib
            ln -s /usr/local/opt/gmp/lib/libgmp.a static-lib/libgmp.a
            export LIBRARY_PATH="$(pwd)/static-lib:${LIBRARY_PATH:-}"
            opts="$opts --disable-static-link"
          fi
          ./configure $opts

      - name: Build
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
              export LIBRARY_PATH="$(pwd)/static-lib:${LIBRARY_PATH:-}"
          fi
          make -j 4
        
      - name: Test
        run: make check

      - name: Print executable information
        run: |
          binname=${{ matrix.bin }}
          if [ "$RUNNER_OS" == "Windows" ]; then
            binname=$binname.exe
          fi
          ls -l sources/$binname
          file sources/$binname
          if [ "$RUNNER_OS" == "macOS" ]; then
            otool -L sources/$binname
            # Check if brewed libraries are statically linked.
            if otool -L sources/$binname | grep -q '/usr/local/opt'; then
              echo 'Error: failed to statically link to brewed libraries' >&2
              exit 1
            fi
          fi

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.bin }}-${{ matrix.os }}
          path: |
            sources/${{ matrix.bin }}
            sources/${{ matrix.bin }}.exe
          if-no-files-found: error
