name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  # This quick check aims to perform a simple build and test on Linux; except
  # the ParFORM case, it probably passes unless the committer has forgotten
  # running "make check".
  quick-check:
    name: Quick check for ${{ matrix.bin }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bin: [form, tform, parform]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensures a reachable tag

      - name: Set up MPI if necessary
        uses: mpi4py/setup-mpi@v1
        if: ${{ matrix.bin == 'parform' }}

      - name: Configure
        run: |
          opts='--disable-dependency-tracking --disable-scalar --disable-threaded --disable-parform --disable-debug --with-gmp --with-zlib'
          case ${{ matrix.bin }} in
            form)    opts="$opts --enable-scalar";;
            tform)   opts="$opts --enable-threaded";;
            parform) opts="$opts --enable-parform";;
          esac
          autoreconf -i
          ./configure $opts

      - name: Build
        run: |
          make -j 4

      - name: Test
        run: |
          make check

  # Check memory errors (e.g., uninitialized values and memory leaks)
  # thoroughly by using Valgrind on Linux.
  valgrind-check:
    name: Valgrind check for ${{ matrix.bin }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bin: [vorm, tvorm, parvorm]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ensures a reachable tag

      - name: Install Valgrind
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: valgrind
          version: 1.0

      - name: Set up MPI if necessary
        uses: mpi4py/setup-mpi@v1
        if: ${{ matrix.bin == 'parvorm' }}

      - name: Configure
        run: |
          opts='--disable-dependency-tracking --disable-scalar --disable-threaded --disable-parform --enable-debug --with-gmp --with-zlib'
          case ${{ matrix.bin }} in
            vorm)    opts="$opts --enable-scalar";;
            tvorm)   opts="$opts --enable-threaded";;
            parvorm) opts="$opts --enable-parform";;
          esac
          autoreconf -i
          ./configure $opts

      - name: Build
        run: |
          make -C sources -j 4 ${{ matrix.bin }}

      - name: Test
        run: |
          ./check/check.rb valgrind ./sources/${{ matrix.bin }} --stat




  # sanitizer-check:
  #   name: Sanitizer check for ${{ matrix.name }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       name:
  #         - vorm-gmp-zlib
  #         - vorm-nogmp-zlib
  #         - vorm-gmp-nozlib
  #         - vorm-nogmp-nozlib
  #         - tvorm-gmp-zlib
  #         - tvorm-nogmp-zlib
  #         - tvorm-gmp-nozlib
  #         - tvorm-nogmp-nozlib
  #         - parvorm-gmp-zlib
  #         - parvorm-nogmp-zlib
  #         - parvorm-gmp-nozlib
  #         - parvorm-nogmp-nozlib
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0  # at least a tag must be reachable

  #     - name: Configure
  #       run: |
  #         opts='--disable-dependency-tracking --disable-scalar --disable-threaded --disable-parform --enable-debug --enable-sanitize'
  #         case ${{ matrix.name }} in
  #           vorm-*-*)
  #             opts="$opts --enable-scalar"
  #             ;;
  #           tvorm-*-*)
  #             opts="$opts --enable-threaded"
  #             ;;
  #           parvorm-*-*)
  #             opts="$opts --enable-parform"
  #             ;;
  #         esac
  #         case ${{ matrix.name }} in
  #           *-gmp-*)
  #             opts="$opts --with-gmp"
  #             ;;
  #           *-nogmp-*)
  #             opts="$opts --without-gmp"
  #             ;;
  #         esac
  #         case ${{ matrix.name }} in
  #           *-zlib-*)
  #             opts="$opts --with-zlib"
  #             ;;
  #           *-nozlib-*)
  #             opts="$opts --without-zlib"
  #             ;;
  #         esac
  #         autoreconf -i
  #         ./configure $opts

  #     - name: Build
  #       run: |
  #         bin=$([[ "${{ matrix.name }}" =~ ^(.*)-.*-.*$ ]] && echo "${BASH_REMATCH[1]}")
  #         make -j 4 -C sources "$bin"

  #     - name: Test
  #       run: |
  #         bin=$([[ "${{ matrix.name }}" =~ ^(.*)-.*-.*$ ]] && echo "${BASH_REMATCH[1]}")
  #         ./check/check.rb "./sources/$bin"  --stat --timeout 60

  # test:
  #   name: Test on ${{ matrix.os }}
  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       os: [ubuntu-latest, macos-latest, windows-latest]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0  # at least a tag must be reachable

  #     - name: Configure
  #       run: |
  #          autoreconf -i
  #          ./configure --disable-dependency-tracking --enable-debug --enable-sanitize

  #     - name: Build
  #       run: make -j 4

  #     - name: Test
  #       run: make check
