name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FORM_IGNORE_DEPRECATION: 1
  OMPI_MCA_rmaps_base_oversubscribe: 1

jobs:
  check-oses:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-13
          - macos-15
          - windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # ensures a reachable tag

      - name: Set up build
        uses: ./.github/actions/setup-build
        with:
          features: form tform ${{ runner.os == 'Windows' && 'msys2' || '' }} hyperfine noconfigure

      # - name: Build
      #   run: make -j 4

      # - name: Test
      #   run: make check

      # - name: Test 2
      #   run: hyperfine 'sleep 1'
